spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/fileuploader
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost:5432/fileuploader
    user: postgres
    password: postgres
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080

storage:
  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: uploads